foo(){
  NATOMS=$1
  for SAMPLING in 2.0 3.0 4.0; do
	    #echo D:/Software/FlexibleRefinement/x64/Release_float/volume_2_pseudoatoms.exe  -i D:/EMD/9233/emd_9233_Scaled_1.5.mrc -o D:/EMD/9233/AtomNumberSweep/output_N${NATOMS}k_OS${SAMPLING} --initialSeeds ${NATOMS}000 --oversampling ${SAMPLING} --mask binary_file --maskfile D:/EMD/9233/emd_9233_Scaled_1.5_mask.mrc --InterpolateValues true --dontAllowMovement  true --dontAllowIntensity true --dontAllowNumberChange false -v 3
	    #D:/Software/FlexibleRefinement/x64/Release_float/volume_2_pseudoatoms.exe  -i D:/EMD/9233/emd_9233_Scaled_1.5.mrc -o D:/EMD/9233/AtomNumberSweep/output_N${NATOMS}k_OS${SAMPLING} --initialSeeds ${NATOMS}000 --oversampling ${SAMPLING} --mask binary_file --maskfile D:/EMD/9233/emd_9233_Scaled_1.5_mask.mrc --InterpolateValues true --dontAllowMovement  true --dontAllowIntensity true --dontAllowNumberChange false -v 3 --thr 16
		echo D:/Software/FlexibleRefinement/x64/Release_float/volume_2_pseudoatoms.exe  -i D:/EMD/9233/AtomNumberSweep/output_N${NATOMS}k_OS${SAMPLING}_approximation.mrc -o D:/EMD/9233/AtomNumberSweep/output_N${NATOMS}k_OS${SAMPLING}_round2 --initialSeeds ${NATOMS}000 --oversampling ${SAMPLING} --mask binary_file --maskfile D:/EMD/9233/emd_9233_Scaled_1.5_mask.mrc --InterpolateValues true --dontAllowMovement  true --dontAllowIntensity true --dontAllowNumberChange false -v 3
		D:/Software/FlexibleRefinement/x64/Release_float/volume_2_pseudoatoms.exe  -i D:/EMD/9233/AtomNumberSweep/output_N${NATOMS}k_OS${SAMPLING}_approximation.mrc -o D:/EMD/9233/AtomNumberSweep/output_N${NATOMS}k_OS${SAMPLING}_round2 --initialSeeds ${NATOMS}000 --oversampling ${SAMPLING} --mask binary_file --maskfile D:/EMD/9233/emd_9233_Scaled_1.5_mask.mrc --InterpolateValues true --dontAllowMovement  true --dontAllowIntensity true --dontAllowNumberChange false -v 3&
		echo D:/Software/FlexibleRefinement/x64/Release_float/volume_2_pseudoatoms.exe  -i D:/EMD/9233/AtomNumberSweep/output_N${NATOMS}k_OS${SAMPLING}_round2_approximation.mrc -o D:/EMD/9233/AtomNumberSweep/output_N${NATOMS}k_OS${SAMPLING}_round3 --initialSeeds ${NATOMS}000 --oversampling ${SAMPLING} --mask binary_file --maskfile D:/EMD/9233/emd_9233_Scaled_1.5_mask.mrc --InterpolateValues true --dontAllowMovement  true --dontAllowIntensity true --dontAllowNumberChange false -v 3
		D:/Software/FlexibleRefinement/x64/Release_float/volume_2_pseudoatoms.exe  -i D:/EMD/9233/AtomNumberSweep/output_N${NATOMS}k_OS${SAMPLING}_round2_approximation.mrc -o D:/EMD/9233/AtomNumberSweep/output_N${NATOMS}k_OS${SAMPLING}_round3 --initialSeeds ${NATOMS}000 --oversampling ${SAMPLING} --mask binary_file --maskfile D:/EMD/9233/emd_9233_Scaled_1.5_mask.mrc --InterpolateValues true --dontAllowMovement  true --dontAllowIntensity true --dontAllowNumberChange false -v 3 &
		echo D:/Software/FlexibleRefinement/x64/Release_float/volume_2_pseudoatoms.exe  -i D:/EMD/9233/AtomNumberSweep/output_N${NATOMS}k_OS${SAMPLING}_round3_approximation.mrc -o D:/EMD/9233/AtomNumberSweep/output_N${NATOMS}k_OS${SAMPLING}_round4 --initialSeeds ${NATOMS}000 --oversampling ${SAMPLING} --mask binary_file --maskfile D:/EMD/9233/emd_9233_Scaled_1.5_mask.mrc --InterpolateValues true --dontAllowMovement  true --dontAllowIntensity true --dontAllowNumberChange false -v 3
		D:/Software/FlexibleRefinement/x64/Release_float/volume_2_pseudoatoms.exe  -i D:/EMD/9233/AtomNumberSweep/output_N${NATOMS}k_OS${SAMPLING}_round3_approximation.mrc -o D:/EMD/9233/AtomNumberSweep/output_N${NATOMS}k_OS${SAMPLING}_round4 --initialSeeds ${NATOMS}000 --oversampling ${SAMPLING} --mask binary_file --maskfile D:/EMD/9233/emd_9233_Scaled_1.5_mask.mrc --InterpolateValues true --dontAllowMovement  true --dontAllowIntensity true --dontAllowNumberChange false -v 3
	done
  sleep 1
}

for N in 100 200 400  600  800 1000; do
	foo $N > D:/EMD/9233/AtomNumberSweep/${N}.log
done